mpc_platform_ouvrage:
    resource: "@mpcPlatformBundle/Controller/OuvrageController.php"
    type:     annotation

mpc_platform:
    resource: "@mpcPlatformBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"