mpc_platform_homepage:
    path:     /
    defaults: { _controller: mpcPlatformBundle:Default:index }
    
ouvrage_nouveautes:
    path:    /nouveautes
    defaults: { _controller: mpcPlatformBundle:Default:nouveautes }
    
ouvrage_ajoutreservations:
    path:    /ajoutreservation
    defaults: { _controller: mpcPlatformBundle:Default:ajoutReservation }
    
ouvrage_mesreservations:
    path:    /mes-reservations
    defaults: { _controller: mpcPlatformBundle:Default:mesReservation }
    
ouvrage_listereservations:
    path:    /liste-reservations
    defaults: { _controller: mpcPlatformBundle:Default:listeReservation }
    
ouvrage_ajoutemprunt:
    path:    /ajoutemprunt
    defaults: { _controller: mpcPlatformBundle:Default:ajoutEmprunt }
    
ouvrage_mesemprunts:
    path:    /mes-emprunts
    defaults: { _controller: mpcPlatformBundle:Default:mesEmprunts }
    
ouvrage_listeEmprunts:
    path:    /liste-emprunts
    defaults: { _controller: mpcPlatformBundle:Default:listeEmprunts }
    
evenements:
    path:    /evenements
    defaults: { _controller: mpcPlatformBundle:Default:indexEvenement }
    
all_evenements:
    path:    /allevents
    defaults: { _controller: mpcPlatformBundle:Default:allEvenements}
    
del_reservation:
    path:    /del-reservation
    defaults: { _controller: mpcPlatformBundle:Default:delReservation }