mpc_platform_homepage:
    path:     /
    defaults: { _controller: mpcPlatformBundle:Default:index }
    
filter_bd:
    path:    /bd
    defaults: { _controller: mpcPlatformBundle:Default:trieBd }
    
filter_livre:
    path:    /livre
    defaults: { _controller: mpcPlatformBundle:Default:trieLivre }
    
filter_cd:
    path:    /cd
    defaults: { _controller: mpcPlatformBundle:Default:trieCd }